### ISSUE TITLE
Is it possible to set a new input+value or add custom HTML to the form?

### ISSUE THREAD

**Issue by henriquelino** [LaunchPlatform/wtforms-bootstrap5#3]
Hey guys, thanks for the amazing library, some context for what I'm doing:

A CRUD with FastAPI, basically.

I managed to transform my SQLALchemy schemas to a form with [wtforms-sqlalchemy](https://github.com/wtforms/wtforms-sqlalchemy), but the form wasn't fitting very well as I was using bootstrap and the form was very crude, so I'm using this lib to beautify the generated form.

I generate the form with:
```python
from wtforms_sqlalchemy.orm import model_form
MyForm = model_form(MyClass)
form = MyForm()
```

then on my HTML I only do this, since it contains all `<form>` in renderer:
```jinja
{{
  render_context
    .form(action=request.url_for('update_myclass'))
    .render(form)
}}
```

So far it's working, but I'm facing some struggles:
* It would be amazing if I can create the submit button with the RenderContext, as wtforms sqlalchemy does not generate a submit button I need to create a parent class that has submitted option and inherit Form this class then reorder the fields then........ it's a workaround.

* I can't manage to post my class ID/PK to be updated as well, if I were doing with pure HTML I would set a new hidden field with the ID, e.g: `<input type="hidden" name="id" value="6">` 

I was thinking about something like:

```jinja
{{
  render_context
    .form(action=request.url_for('update_myclass'))
    .post_params(name="id", value"123"),
    .add_submit_button(name="save, send, update, some text for button"),
    .render(form)
}}
```
If this isn't the way or have another method of doing those two things I would love to hear, so far I was thinking of getting the generated HTML and injecting those fields I need, but this doesn't feel right tbh, I think it would be less ugly if I could inject something in the middle of the generated HTML of the renderer directly.

**Comment by henriquelino** [comment]
update: I totally forgot I could pass the ID via url parameter, so I managed to do that with:
```
{{
  render_context
    .form(action=request.url_for('update_endpoint', id=myclass.id) )
    .render(form)
}}
```

---
for adding button, I could remove `<form>` tag then rebuild the form:
```python
# in my view
context = RendererContext()
html = str(context.form().render(form))
html = html.replace('<form method="POST">', '')
html = html.replace('</form>', '')
html = Markup(html)
# pass html to context and use in jinja

return templates.TemplateResponse("mytemplate.html", {"html_form": html})
```

in html:
```html
<form method="POST" action="{{ request.url_for('update', id=myclass.id) }}">
  {{ html_form }}
  <input type="hidden" name="myhiddenfield" value="somevalue">
  <div class="mb-3">
    <input class="btn btn-primary" id="submit" name="submit" type="submit" value="Submit">
  </div>
</form>
```

**Comment by fangpenlin** [comment]
Hi @henriquelino, thanks for reporting the issue. I realize that I need similar feature as you described, so I am working on #4 to address this feature. The PR will be merged shortly and a new release will be made.

For your second approach, to stop form tag from generating, actually you don't need to replace the form tags. You only need to use the `form_enabled` option like this

```python
renderer_context.form(form_enabled=False).render(form)
```

Sorry it's not mentioned in the document, so you might not know that.
